name: Deploy on labeled/unlabeled issue
on:
  issues:
    types:
      - labeled
      - unlabeled
jobs:
  deploy:
    name: Checkout and Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Get BUILD_DATE
        id: date
        run: echo "::set-output name=BUILD_DATE::$(date '+%a, %d %b %Y %H:%M:%S GMT')"
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Publish Worker
        if: github.event.label == 'public'
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: 'production'
          publish: false
          preCommands: |
            wrangler build --env=production
          postCommands: |
            echo "*** Clear cache ***"
            wrangler kv:key list --binding=CACHED_RESPONSE --env=production | xargs -0 -i node -pe 'JSON.stringify({}.map(a => { return {"key": a.name, "value": ""}; }))' > cache.json
            echo "y"|wrangler kv:bulk delete --env=production --binding=CACHED_RESPONSE cache.json
            echo "******"
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          BUILD_DATE: ${{ steps.date.outputs.BUILD_DATE }}
      - name: Create Cache
        run: |
          curl https://waka.dev
          curl https://waka.dev/archive
          curl https://waka.dev/feed.xml
